include:
  - local: "data-creator/.gitlab-ci.yml"
  - local: "feach/.gitlab-ci.yml"
  - local: "ml-worker/.gitlab-ci.yml"
  - local: "adminka/.gitlab-ci.yml"
  - local: "price-checker/.gitlab-ci.yml"

