name: infra
services:
  kafka:
    image: akitavi/bkafka:latest
    ports:
      - "9094:9094"
      - "9092:9092"
    restart: unless-stopped
    environment:
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_PROCESS_ROLES: "controller,broker"
      KAFKA_CFG_NODE_ID: "1"

      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

      KAFKA_CFG_LISTENERS: "INTERNAL://:9092,EXTERNAL://:9094,CONTROLLER://:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "INTERNAL://kafka:9092,EXTERNAL://localhost:9094"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"

      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "INTERNAL"

      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: "1"

      ALLOW_PLAINTEXT_LISTENER: "yes"
    networks:
      - shared-net

  exporter-kafka:
    image: danielqsj/kafka-exporter:latest
    restart: unless-stopped
    environment:
      - KAFKA_SERVER=kafka:9092  # Адрес вашего брокера Kafka
    ports:
      - "9308:9308"  # Порт, на котором экспортёр будет слушать
    depends_on:
      - kafka
    networks:
      - shared-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
    networks:
      - shared-net

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web UI
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - shared-net

  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.97.0
    ports:
      - "8428:8428"
    command:
      - "-storageDataPath=/storage"
    volumes:
      - vmdata:/storage
  
  vmagent:
    image: victoriametrics/vmagent:v1.97.0
    depends_on:
      - victoriametrics
    volumes:
      - ./vmagent.yml:/etc/vmagent.yml:ro
    command:
      - "-promscrape.config=/etc/vmagent.yml"
      - "-remoteWrite.url=http://victoriametrics:8428/api/v1/write"
    restart: unless-stopped
    networks:
      - shared-net


  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - victoriametrics
    volumes:
      - grafana-data:/var/lib/grafana  # Это место, где Grafana хранит свои данные
      - ./dashboard:/etc/grafana/provisioning/dashboards 
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - shared-net


volumes:
  vmdata: {}
  minio-data: {}
  grafana-data: {} 

networks:
  shared-net:
    external: true
    name: shared-net
